# Generated by Django 5.2.13 on 2026-05-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_and_more'),
        ('viewer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewevent',
            options={'verbose_name': '열람 이벤트', 'verbose_name_plural': '열람 이벤트'},
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소'),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='official_pdf_sha256',
            field=models.CharField(max_length=64, verbose_name='공식 PDF SHA-256'),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='view_events', to='documents.documentrevision', verbose_name='리비전'),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='viewevent',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='열람일시'),
        ),
    ]
