# Generated by Django 5.2.13 on 2026-05-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_and_more'),
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfconversionjob',
            options={'verbose_name': 'PDF 변환 작업', 'verbose_name_plural': 'PDF 변환 작업'},
        ),
        migrations.AlterModelOptions(
            name='qaexception',
            options={'verbose_name': 'QA 예외', 'verbose_name_plural': 'QA 예외'},
        ),
        migrations.AlterField(
            model_name='pdfconversionjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='완료일시'),
        ),
        migrations.AlterField(
            model_name='pdfconversionjob',
            name='converter_version',
            field=models.CharField(blank=True, max_length=255, verbose_name='변환기 버전'),
        ),
        migrations.AlterField(
            model_name='pdfconversionjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='pdfconversionjob',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='오류 메시지'),
        ),
        migrations.AlterField(
            model_name='pdfconversionjob',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_job', to='documents.documentrevision', verbose_name='리비전'),
        ),
        migrations.AlterField(
            model_name='pdfconversionjob',
            name='status',
            field=models.CharField(choices=[('Pending', '대기중'), ('Succeeded', '성공'), ('Failed', '실패')], default='Pending', max_length=24, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='qaexception',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='qaexception',
            name='exception_type',
            field=models.CharField(max_length=120, verbose_name='예외 유형'),
        ),
        migrations.AlterField(
            model_name='qaexception',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='해결됨'),
        ),
        migrations.AlterField(
            model_name='qaexception',
            name='message',
            field=models.TextField(verbose_name='메시지'),
        ),
        migrations.AlterField(
            model_name='qaexception',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_exceptions', to='documents.documentrevision', verbose_name='리비전'),
        ),
    ]
