#!/usr/bin/env node
// Generate TypeScript types from the backend OpenAPI spec.
// Reads /v3/api-docs.json (springdoc default) and writes src/api/schema.d.ts.
//
// Usage:
//   npm run gen:api                              # uses http://localhost:8080
//   API_URL=http://host:port/v3/api-docs.json npm run gen:api

import openapiTS, { astToString } from 'openapi-typescript';
import { writeFileSync } from 'node:fs';

const SPEC_URL = process.env.API_URL ?? 'http://localhost:8080/v3/api-docs.json';
const OUTPUT = new URL('../src/api/schema.d.ts', import.meta.url);

const HEADER = `// Auto-generated by scripts/gen-api.mjs
// Run: npm run gen:api
// DO NOT EDIT MANUALLY
`;

try {
  console.log(`[gen:api] fetching OpenAPI spec from ${SPEC_URL} ...`);
  const ast = await openapiTS(new URL(SPEC_URL));
  const body = astToString(ast);
  writeFileSync(OUTPUT, HEADER + body);
  console.log(`[gen:api] wrote ${OUTPUT.pathname}`);
} catch (err) {
  console.error('[gen:api] failed to generate types.');
  console.error(`  spec URL: ${SPEC_URL}`);
  console.error('  Is the backend running and reachable?');
  console.error('  Tip: start it with `./gradlew :backend:bootRun` (default port 8080).');
  if (err && err.message) console.error(`  reason: ${err.message}`);
  process.exit(1);
}
