package com.lab.edms.audit;

public enum AuditAction {
    // M1
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAIL,
    USER_LOGOUT,
    USER_PASSWORD_CHANGED,
    USER_LOCKED,
    USER_UNLOCKED,
    USER_FORCED_CHANGE_PW,

    // M2
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_PASSWORD_RESET,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    ROLE_UPDATED,
    PERMISSION_GRANTED,
    PERMISSION_UPDATED,
    PERMISSION_REVOKED,
    ACCOUNT_AUTO_UNLOCKED,
    AUDITOR_EXPIRED,
    AUDITOR_EXPIRY_WARNING,
    USER_LAST_LOGIN_UPDATED,

    // M3
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DOCUMENT_CATEGORY_CREATED,
    DOCUMENT_CATEGORY_UPDATED,
    NUMBERING_TEMPLATE_CREATED,
    NUMBERING_TEMPLATE_UPDATED,
    DOCUMENT_CREATED,
    DOCUMENT_FILE_UPLOADED,
    DOCUMENT_METADATA_UPDATED,
    DOCUMENT_VIEWED
}
