package com.lab.edms.audit;

public enum AuditAction {
    // M1
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAIL,
    USER_LOGOUT,
    USER_PASSWORD_CHANGED,
    USER_LOCKED,
    USER_UNLOCKED,
    USER_FORCED_CHANGE_PW,

    // M2
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_PASSWORD_RESET,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    ROLE_UPDATED,
    PERMISSION_GRANTED,
    PERMISSION_UPDATED,
    PERMISSION_REVOKED,
    ACCOUNT_AUTO_UNLOCKED,
    AUDITOR_EXPIRED,
    AUDITOR_EXPIRY_WARNING,
    USER_LAST_LOGIN_UPDATED,

    // M3
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DOCUMENT_CATEGORY_CREATED,
    DOCUMENT_CATEGORY_UPDATED,
    NUMBERING_TEMPLATE_CREATED,
    NUMBERING_TEMPLATE_UPDATED,
    DOCUMENT_CREATED,
    DOCUMENT_FILE_UPLOADED,
    DOCUMENT_METADATA_UPDATED,
    DOCUMENT_VIEWED,

    // === M4: Lifecycle & Workflow ===
    WORKFLOW_TEMPLATE_CREATED,
    WORKFLOW_TEMPLATE_UPDATED,
    WORKFLOW_TEMPLATE_DELETED,
    WORKFLOW_SUBMITTED,
    WORKFLOW_STEP_SIGNED,
    WORKFLOW_STEP_COMPLETED,
    WORKFLOW_STEP_REJECTED,
    WORKFLOW_REJECTED,
    WORKFLOW_COMPLETED,
    STATE_TRANSITION,
    DOCUMENT_VERSION_EFFECTIVE,
    DOCUMENT_VERSION_SUPERSEDED,
    DOCUMENT_VERSION_RETIRED,
    REVISION_STARTED,

    // === M5: WORM Audit Anchor ===
    WORM_ANCHOR_CREATED,
    WORM_ANCHOR_FAILED,

    // M7.1: PDF Viewer (do NOT conflict with DOCUMENT_VIEWED from M3)
    PDF_VIEWED,
    PDF_DOWNLOADED,
    PDF_VERIFIED,
    PDF_VIEW_DENIED,
    PDF_DOWNLOAD_DENIED,

    // M7.5: Research project lifecycle + retention
    RESEARCH_PROJECT_REGISTERED,
    RESEARCH_PROJECT_APPROVED,
    RESEARCH_PROJECT_TERMINATED,
    RETENTION_EXTENSION_FAILED,
    RETENTION_FEATURE_TOGGLED
}
