# Generated by Django 5.2.13 on 2026-05-01 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('numbering_prefix_template', models.CharField(default='{project_code}-{document_type}-', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Draft Uploaded', 'Draft Uploaded'), ('In Review', 'In Review'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Effective', 'Effective'), ('Superseded', 'Superseded'), ('Retired', 'Retired')], default='Reserved', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('source_file', models.FileField(upload_to='sources/%Y/%m/')),
                ('source_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('official_pdf', models.FileField(blank=True, upload_to='official_pdfs/%Y/%m/')),
                ('official_pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Draft Uploaded', 'Draft Uploaded'), ('In Review', 'In Review'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Effective', 'Effective'), ('Superseded', 'Superseded'), ('Retired', 'Retired')], default='Draft Uploaded', max_length=32)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='documents.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentrevision'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype'),
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.projectcode')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.projectcode'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'revision'), name='unique_revision_per_document'),
        ),
        migrations.AddConstraint(
            model_name='documentnumbersequence',
            constraint=models.UniqueConstraint(fields=('project_code', 'document_type'), name='unique_sequence_per_project_type'),
        ),
    ]
