# Generated by Django 5.2.13 on 2026-05-01 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '문서', 'verbose_name_plural': '문서'},
        ),
        migrations.AlterModelOptions(
            name='documentnumbersequence',
            options={'verbose_name': '문서번호 시퀀스', 'verbose_name_plural': '문서번호 시퀀스'},
        ),
        migrations.AlterModelOptions(
            name='documentrevision',
            options={'verbose_name': '리비전', 'verbose_name_plural': '리비전'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': '문서 유형', 'verbose_name_plural': '문서 유형'},
        ),
        migrations.AlterModelOptions(
            name='projectcode',
            options={'verbose_name': '프로젝트 코드', 'verbose_name_plural': '프로젝트 코드'},
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='document',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documentrevision', verbose_name='현재 리비전'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=120, unique=True, verbose_name='문서번호'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='문서 유형'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.projectcode', verbose_name='프로젝트 코드'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Reserved', '예약됨'), ('Draft Uploaded', '초안 업로드'), ('In Review', '결재 진행중'), ('Rejected', '반려됨'), ('Cancelled', '취소됨'), ('Approved', '승인됨'), ('Effective', '발효됨'), ('Superseded', '대체됨'), ('Retired', '폐기됨')], default='Reserved', max_length=32, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='documentnumbersequence',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='문서 유형'),
        ),
        migrations.AlterField(
            model_name='documentnumbersequence',
            name='next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='다음 번호'),
        ),
        migrations.AlterField(
            model_name='documentnumbersequence',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.projectcode', verbose_name='프로젝트 코드'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='documents.document', verbose_name='문서'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='effective_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='발효일시'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='official_pdf',
            field=models.FileField(blank=True, upload_to='official_pdfs/%Y/%m/', verbose_name='공식 PDF'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='official_pdf_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='공식 PDF SHA-256'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='revision',
            field=models.PositiveIntegerField(verbose_name='리비전 번호'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='source_file',
            field=models.FileField(upload_to='sources/%Y/%m/', verbose_name='원본 파일'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='source_filename',
            field=models.CharField(max_length=255, verbose_name='원본 파일명'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='source_sha256',
            field=models.CharField(max_length=64, verbose_name='원본 SHA-256'),
        ),
        migrations.AlterField(
            model_name='documentrevision',
            name='status',
            field=models.CharField(choices=[('Reserved', '예약됨'), ('Draft Uploaded', '초안 업로드'), ('In Review', '결재 진행중'), ('Rejected', '반려됨'), ('Cancelled', '취소됨'), ('Approved', '승인됨'), ('Effective', '발효됨'), ('Superseded', '대체됨'), ('Retired', '폐기됨')], default='Draft Uploaded', max_length=32, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='문서 유형 코드'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='문서 유형명'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='numbering_prefix_template',
            field=models.CharField(default='{project_code}-{document_type}-', max_length=120, verbose_name='번호 접두 템플릿'),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='프로젝트 코드'),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='name',
            field=models.CharField(max_length=255, verbose_name='프로젝트명'),
        ),
    ]
