"""numbering_sequences

Revision ID: e29d15704297
Revises: c4fe0396e711
Create Date: 2026-04-26 00:54:23.596940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29d15704297'
down_revision: Union[str, Sequence[str], None] = 'c4fe0396e711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numbering_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('doc_type_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'doc_type_id', 'period')
    )
    op.create_index(op.f('ix_numbering_sequences_doc_type_id'), 'numbering_sequences', ['doc_type_id'], unique=False)
    op.create_index(op.f('ix_numbering_sequences_project_id'), 'numbering_sequences', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_numbering_sequences_project_id'), table_name='numbering_sequences')
    op.drop_index(op.f('ix_numbering_sequences_doc_type_id'), table_name='numbering_sequences')
    op.drop_table('numbering_sequences')
    # ### end Alembic commands ###
