# Generated by Django 5.2.13 on 2026-05-01 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['created_at', 'id'], 'verbose_name': '감사 이벤트', 'verbose_name_plural': '감사 이벤트'},
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='실행자'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='after',
            field=models.JSONField(blank=True, default=dict, verbose_name='변경 후'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='before',
            field=models.JSONField(blank=True, default=dict, verbose_name='변경 전'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_hash',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='이벤트 해시'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(max_length=120, verbose_name='이벤트 유형'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_id',
            field=models.CharField(max_length=120, verbose_name='대상 ID'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(max_length=120, verbose_name='대상 유형'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='prev_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='이전 해시'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='reason',
            field=models.TextField(blank=True, verbose_name='사유'),
        ),
    ]
