# Generated by Django 5.2.13 on 2026-05-01 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0002_alter_document_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalroutestep',
            options={'ordering': ['order'], 'verbose_name': '결재 단계', 'verbose_name_plural': '결재 단계'},
        ),
        migrations.AlterModelOptions(
            name='approvalroutetemplate',
            options={'verbose_name': '결재선 템플릿', 'verbose_name_plural': '결재선 템플릿'},
        ),
        migrations.AlterModelOptions(
            name='approvaltask',
            options={'ordering': ['order', 'id'], 'verbose_name': '결재 작업', 'verbose_name_plural': '결재 작업'},
        ),
        migrations.AlterModelOptions(
            name='electronicsignature',
            options={'verbose_name': '전자서명', 'verbose_name_plural': '전자서명'},
        ),
        migrations.AlterField(
            model_name='approvalroutestep',
            name='order',
            field=models.PositiveIntegerField(verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='approvalroutestep',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='역할'),
        ),
        migrations.AlterField(
            model_name='approvalroutestep',
            name='signature_meaning',
            field=models.CharField(help_text='"검토", "승인" 등 한국어로 입력하세요.', max_length=80, verbose_name='결재 의미'),
        ),
        migrations.AlterField(
            model_name='approvalroutestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalroutetemplate', verbose_name='결재선'),
        ),
        migrations.AlterField(
            model_name='approvalroutetemplate',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_templates', to='documents.documenttype', verbose_name='문서 유형'),
        ),
        migrations.AlterField(
            model_name='approvalroutetemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='approvalroutetemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='템플릿명'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='지정 결재자'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='comment',
            field=models.TextField(blank=True, verbose_name='의견'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='완료일시'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='order',
            field=models.PositiveIntegerField(verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to='documents.documentrevision', verbose_name='리비전'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='role_name',
            field=models.CharField(max_length=150, verbose_name='역할명'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='route_template_name',
            field=models.CharField(max_length=255, verbose_name='결재선명'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='signature_meaning',
            field=models.CharField(max_length=80, verbose_name='결재 의미'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='status',
            field=models.CharField(choices=[('Pending', '대기중'), ('Approved', '승인'), ('Rejected', '반려'), ('Cancelled', '취소')], default='Pending', max_length=24, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='auth_method',
            field=models.CharField(default='password_reentry', max_length=80, verbose_name='인증 방식'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='meaning',
            field=models.CharField(max_length=80, verbose_name='결재 의미'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='서명일시'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='서명자'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='source_sha256',
            field=models.CharField(max_length=64, verbose_name='원본 SHA-256'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature', to='approvals.approvaltask', verbose_name='결재 작업'),
        ),
    ]
